name: 📋 Task
description: 새로운 작업이나 할 일을 등록합니다.
title: "[Task]: "
labels: ["task", "todo"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        새로운 작업을 등록해주셔서 감사합니다. 작업 내용을 구체적으로 작성해주세요.
  
  - type: textarea
    id: description
    attributes:
      label: 작업 설명
      description: 무엇을 해야 하는지 자세히 설명해주세요.
      placeholder: 작업의 목적과 범위를 명확히 작성해주세요.
    validations:
      required: true
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 완료 조건
      description: 이 작업이 완료되었다고 판단할 수 있는 기준을 작성해주세요.
      placeholder: |
        - [ ] 기준 1
        - [ ] 기준 2
        - [ ] 기준 3
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 이 작업의 우선순위를 선택해주세요.
      options:
        - 🔴 긴급 (Urgent)
        - 🟠 높음 (High)
        - 🟡 보통 (Medium)
        - 🟢 낮음 (Low)
    validations:
      required: true
  
  - type: dropdown
    id: category
    attributes:
      label: 카테고리
      description: 작업의 유형을 선택해주세요.
      options:
        - 개발 (Development)
        - 디자인 (Design)
        - 문서화 (Documentation)
        - 테스트 (Testing)
        - 리팩토링 (Refactoring)
        - 인프라 (Infrastructure)
        - 기타 (Other)
    validations:
      required: false
  
  - type: input
    id: estimate
    attributes:
      label: 예상 소요 시간
      description: 작업에 걸릴 것으로 예상되는 시간을 입력해주세요.
      placeholder: "예: 2시간, 1일, 3일"
    validations:
      required: false
  
  - type: input
    id: due-date
    attributes:
      label: 마감일
      description: 작업의 마감일이 있다면 입력해주세요.
      placeholder: "예: 2025-10-20"
    validations:
      required: false
  
  - type: textarea
    id: subtasks
    attributes:
      label: 하위 작업 (선택)
      description: 이 작업을 더 작은 단위로 나눌 수 있다면 리스트로 작성해주세요.
      placeholder: |
        - [ ] 하위 작업 1
        - [ ] 하위 작업 2
        - [ ] 하위 작업 3
      render: markdown
    validations:
      required: false
  
  - type: textarea
    id: dependencies
    attributes:
      label: 의존성
      description: 이 작업을 시작하기 전에 완료되어야 할 다른 작업이 있나요?
      placeholder: "#123, #456"
    validations:
      required: false
  
  - type: textarea
    id: resources
    attributes:
      label: 참고 자료
      description: 작업에 도움이 될 만한 링크, 문서, 디자인 파일 등을 공유해주세요.
      placeholder: |
        - 관련 문서: https://...
        - 디자인 파일: https://...
        - 참고 자료: https://...
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 기타 전달할 내용이 있다면 작성해주세요.
    validations:
      required: false
