name: Discord webhook

on: 
  pull_request:
    types: [synchronize]

jobs:
  call:
    runs-on: bubuntu-latest
    steps:
      - name: Call webhook
        env: 
          WEBHOOK:URL: ${{ secrets.PR_WEBHOOK_URL }}
          PAYLOAD: ${{ toJson(github.event) }}
        run: |
          curl -sS -X POST "$PR_WEBHOOK_URL" \
            -H "Content-Type: applicatin/json" \
            -d "$PAYLOAD"
            
